# Generated by Django 5.2.1 on 2025-09-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
