# Generated by Django 5.2.6 on 2025-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
